app:
    testmodel: false
    debug: true
    apiLogEnabled: false
    acc: !CONFIG_PATH acc.xml
    accessTokenUserIdKey: console.uid
    accessTokenUserFullname: fullname
    jwtTokenSecret:
    name: SYSTEM name
    software_copyright: Design by DONNY &copy 2025
    charset: utf-8
    locale: zh_CN
api:
    0:
        appKey: 1000
        appSecret: " "
dbread:
    adapter: &DB_ADAPTER mysqlnd
    host: &DB_HOST localhost
    port: &DB_PORT 3306
    charset: &DB_CHARSEG utf8mb4
    username: &DB_USER root
    password: &DB_PASSWORD admin
    dbname: &DB_NAME test
dbwrite:
    adapter: *DB_ADAPTER
    host: *DB_HOST
    port: *DB_PORT
    charset: *DB_CHARSEG
    username: *DB_USER
    password: *DB_PASSWORD
    dbname: *DB_NAME

redis:
    host: localhost
    port: 6379
    auth:
    index: 0
    prefix:
    lifetime: 3600

aliyun:
    sts:
        accessKeyId:
        aAccessKeySecret:
        roleArn:
        tokenExpireTime: 3600
        policyFile: !CONFIG_PATH aliyunoss/policy-all.txt
        roleSessionName:
    server:
        accessKeyId:
        aAccessKeySecret:

aliyunoss:
    bucket:
        region:
        name:
        endpoint:
        host:

aliyunsms:
    regionId:
    appKey:
    appSecret:
    signName:
    managerMobiles: ""
    template:
        changePasswd:
        register:
        verify:

aliyunemail:
    appKey:
    appSecret:
    regionId: cn-hangzhou
    triggerEmail: ""
    templateDir: !CONFIG_PATH email-tpls
cache:
    slow:
        engine: stream
        option:
            storageDir: /tmp
            lifetime: 86400
    fast:
        engine: redis


weixin:
    token: ""
    appid: ""
    appsecret: ""
    notcheck: true

queue:
    adapter: redis

filestorage:
    # adapter: localfile, aliyun
    adapter: aliyun
    localfile:
        hostUrl: ""
        baseDir: data
        rootDir: ""
session:
    enabled: false
    #adapter: stream, redis
    adapter: stream
    option:
